import numpy as np
#RL
#Env 
ENV_NAME = 'DeepSea' #'Maze', 'GridWorld'， DeepSea
CORRECT_MOVE_PROB = 0.5
STOCHASTIC = False
#ENV_NAME = 'MountainCar'

#Test parameters
# HORIZON = 15
# #Number of EPISODES
# EPISODES = 2
# GAMMA = 0.95
# REPEAT_EXPERIMENT = 2
# DISCRETE = False
# BINS = (10, )
# LAST_EPISODE = 1
# ONLINE_LEARNING = True
# SEED = 555
# FROZEN_T = 5

#Long Experiment
HORIZON = 100
#Number of EPISODES
EPISODES = 2
GAMMA = 1
REPEAT_EXPERIMENT = 1
DISCRETE = False
BINS = (10, )
LAST_EPISODE = 1
ONLINE_LEARNING = True
SEED = 555
FROZEN_T = HORIZON #15
BATCH_TRAINING = False
BATCH_SIZE = 64
BUFFER_SIZE = 100 if BATCH_TRAINING else 100000000000
GREEDY = False
GREEDY_EPSILON = 0
UNIQUE_OBS = True


#SMC parameters
PRIOR = 'normal'
LLD = 'normal'
N_PARTICLE = 4
MIN_ESS = 0.5
ESS_ALPHA = 0.8

#MCMC
PRIOR_SIGMA = 2
PRIOR_MEAN = 0
UPDATE_FREQUENCY = 5
INITIAL_STEPSIZE = STEPSIZE = 1e-2
DECREASING_FACTOR = 1.0
MCMC_T = 10000
MCMC_SHOW_DISABLE = False
MCMC_SAMPLE = 3
BURN_IN = 0.1
SKIP = 10
TARGET_ACCEPT_PROB = 0.7
WARMUP_RATIO = 0

NUM_STEPS = 1000
TRAJECTORY_LENGTH = 2 * np.pi
MASS = 1
FULL_MASS = False
FROZEN = False
FROZEN_NO = [0, 1] if FROZEN else None
FROZEN_IDX = [(0, 0, 0), (0, 0, 1)] if FROZEN else None
TRANSFORM = False

#Plot
PLOT_THRESHOLD = 2#percentile
OBSERVE_DATA_START = -16
OBSERVE_DATA_END = 100

#ABC
EPSILON = 0.01
M_Z = 1200

#Results
SAVE = False
SHOW = True
