#RL
#Env 
ENV_NAME = 'GridWorld'
#ENV_NAME = 'MountainCar'

#Test parameters
# HORIZON = 15
# #Number of EPISODES
# EPISODES = 2
# GAMMA = 0.95
# REPEAT_EXPERIMENT = 2
# DISCRETE = False
# BINS = (10, )
# LAST_EPISODE = 1
# ONLINE_LEARNING = True
# SEED = 555
# FROZEN_T = 5

#Long Experiment
HORIZON = 100
#Number of EPISODES
EPISODES = 20
GAMMA = 0.95
REPEAT_EXPERIMENT = 4
DISCRETE = False
BINS = (10, )
LAST_EPISODE = 1
ONLINE_LEARNING = True
SEED = 555
FROZEN_T = 15
BATCH_TRAINING = False
BATCH_SIZE = 64
BUFFER_SIZE = 100 if BATCH_TRAINING else 100000000000
GREEDY = False
GREEDY_EPSILON = 0.3


#SMC parameters
PRIOR = 'normal'
LLD = 'normal'
N_PARTICLE = 4
MIN_ESS = 0.5

#MCMC
PRIOR_SIGMA = 10
UPDATE_FREQUENCY = 5
INITIAL_STEPSIZE = STEPSIZE = 0.0001
DECREASING_FACTOR = 0.9
MCMC_T = 1000
MCMC_SHOW_DISABLE = False
MCMC_SAMPLE = 10
BURN_IN = 0.1
SKIP = 10
TARGET_ACCEPT_PROB = 0.4
WARMUP_RATIO = 0
ADAPT_STEP_SIZE = True if WARMUP_RATIO > 0 else False
ADAPT_MASS_MATRIX = True if WARMUP_RATIO > 0 else False
NUM_STEPS = 2000
FULL_MASS = False
#Plot
PLOT_THRESHOLD = 2#percentile

#ABC
EPSILON = 0.05

#Results
SAVE = False
SHOW = True
